// <auto-generated />
namespace DataLogger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class populatechanel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populatechanel));
        
        string IMigrationMetadata.Id
        {
            get { return "202005300719243_populate-chanel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
